export enum StatusCodes {
	INVALID_SINGUP_REQUEST = 400,
	INVALID_LOGIN_REQUEST,
	USER_CREATION_SUCCESFUL,
	USER_CREATION_FAILED,
	USER_NOT_FOUND,
	USER_FOUND,
	PASSWORD_VALIDATION_FAILED,
	PASSWORD_VALIDATION_SUCCESSFUL,
	SIGNUP_FAILED,
	LOGIN_FAILED
}

export default StatusCodes
