export enum StatusCodes {
	INVALID_SINGUP_REQUEST = 400,
	INVALID_LOGIN_REQUEST,
	USER_CREATION_SUCCESFUL,
	USER_CREATION_FAILED,
	USER_NOT_FOUND,
	USER_FOUND,
	PASSWORD_VALIDATION_FAILED,
	PASSWORD_VALIDATION_SUCCESSFUL,
	SIGNUP_FAILED,
	LOGIN_FAILED,
	SIGNUP_SUCCESSFUL,
	LOGIN_SUCCESSFUL,
	DB_CLIENT_INITIALIZATION_FAILED,
	AUTH_TOKEN_NOT_FOUND,
	AUTH_TOKEN_FOUND,
	AUTH_TOKEN_EXPIRED,
	AUTH_TOKEN_INVALID,
	AUTH_TOKEN_NOT_BEFORE_VALID,
	REFRESH_TOKEN_EXPIRED,
	REFRESH_TOKEN_INVALID,
	NEW_ACCESS_TOKEN_CREATED,
	INTERNAL_SERVER_ERROR
}

export default StatusCodes
